### ISSUE TITLE
Aloe not detecting update keyphrase

### ISSUE THREAD

**Issue by matthewjamesr** [leafsphp/aloe#6]
There should be two string patterns when generating migrations, one to create tables and one to update them. Updating should  allow for the changing of previous columns and the insertion of new ones.

Currently, ```php leaf g:migration``` outputs all files as ```create_```, without the appropriate default logic to ammend/add. Below is an example flow of what should occur:

1. Execute command ```php leaf g:migration addAdminLevelToUsers```
2. Create migration with filename: ```YYYY_mm_dd_hhmmss_add_admin_level_to_users```
3. Generate scaffold:
```
<?php

use Leaf\Database;
use Illuminate\Database\Schema\Blueprint;

class AddAdminLevelToUsers extends Database
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        static::$capsule::schema()->table("users", function (Blueprint $table) {
            $column = static::$capsule::schema()->hasColumn("users", "admin_level");
            
            if ($column) {
                $table->integer("admin_level")->default(0)->change();
            } else {
                $table->integer("admin_level")->default(0);
            }
        });

        // you can now build your migrations with schemas
        // Schema::build(static::$capsule, dirname(__DIR__) . "/Schema/users.json");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        static::$capsule::schema()->dropIfExists("users");
    }
}
```

Migrations can then be executed as normal. Utilzing ```change()``` on it's own can cause failures when migration.

**Comment by matthewjamesr** [comment]
The scaffold itself should stop short of outputting the column creation/change code. However, it might be a good idea to allow it to survive as an example in a comment block.

**Comment by mychidarko** [comment]
That's true. This will be added.

**Comment by mychidarko** [comment]
This has been added now. From the next release, you will be able to run commands like this:

```sh
php leaf g:migration addAdminLevelToUsers
```

Which will generate a filename like `YYYY_mm_dd_hhmmss_add_admin_level_to_users` with a pre-built scaffold. By default, leaf uses the information entered to generate the table names for your scaffold. This means you will have `addAdminLevelToUsers` as your table name. To bypass this, a new option has been added `--table` or `-t` for short. You will now have a command like this:

```sh
php leaf g:migration addAdminLevelToUsers -t users
```
